# Numpy

In [1]:
#pip install numpy

In [2]:
# Como importar numpy
import numpy as np
import pandas as pd

ndarray - nd es por n-dimensional  
Es un array multidimensional de elementos del mismo tipo

In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
a[:,[0]]

array([[1],
       [4]])

In [5]:
a[1][1]

5

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
a.trace()

15

In [8]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
c = np.arange(10)

In [12]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linalg.det(a)

0.0

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,2,50)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [18]:
np.eye(1)

array([[1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(4,2,2)

array([[[0.24090781, 0.75749001],
        [0.50369166, 0.05538908]],

       [[0.94177567, 0.72185573],
        [0.39342876, 0.10050748]],

       [[0.17933152, 0.67407808],
        [0.71882276, 0.26505212]],

       [[0.5339999 , 0.57503109],
        [0.1690414 , 0.68256372]]])

In [21]:
np.random.randn(3)

array([-0.11297485,  0.62261771, -0.46255983])

In [22]:
np.random.randint(1, 100,5)

array([67, 31,  5, 88, 50])

In [23]:
arr = np.array([0,1,2,3,4,5])
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr.max()

5

In [25]:
arr.argmax()

5

In [26]:
arr.sum()

15

In [27]:
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
1 + arr

array([1, 2, 3, 4, 5, 6])

In [29]:
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
np.random.seed(40)

In [31]:
np.random.seed(40)
print(np.random.rand(4))

[0.40768703 0.05536604 0.78853488 0.28730518]


In [32]:
np.mean(arr)

2.5

In [33]:
np.var(arr)

2.9166666666666665

In [34]:
np.std(arr)

1.707825127659933

In [35]:
arr < 1

array([ True, False, False, False, False, False])

In [36]:
arr_bool = arr<1
arr_bool

array([ True, False, False, False, False, False])

In [37]:
arr_num = arr[arr<1]
arr_num

array([0])

In [38]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [39]:
w1, w2, w3 = 0.3, 0.2, 0.5
peso = [w1,w2,w3]

In [40]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    
    return result

In [41]:
crop_yield(kanto,peso)

56.8

In [42]:
crop_yield(sinnoh,peso)

57.699999999999996

In [43]:
kanto = np.array(kanto)
kanto

array([73, 67, 43])

In [44]:
peso = np.array(peso)

In [45]:
peso.dtype

dtype('float64')

In [46]:
np.dot(kanto,peso)

56.8

In [47]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [48]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 172 ms
Wall time: 213 ms


833332333333500000

In [49]:
%%time
np.dot(arr1_np, arr2_np)


CPU times: total: 0 ns
Wall time: 0 ns


-1942957984

In [50]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [51]:
np.dot(climate_data,peso).reshape(5,1)

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [52]:
np.matmul(climate_data,peso)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [53]:
climate_data @ peso

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [54]:
array1 = np.array([1])
array2 = np.array([1])

In [55]:
np.matmul(array1,array2)

1

In [56]:
np.random.randint(1,100,100,dtype='int64')

array([13, 72, 20, 32, 75, 56, 84, 60, 92, 74, 97, 50, 54, 74,  9, 53, 31,
       80, 15, 93, 59, 75, 23,  4, 92, 72, 56, 84, 29, 14, 38, 83, 51, 80,
       68, 31, 61, 45, 47, 88, 44, 36, 99, 32, 83,  6, 81, 66,  8, 93, 42,
       96, 89, 94, 26, 84, 59, 99, 71, 58, 58, 84, 86, 37, 64, 75, 89,  1,
        2, 34, 53, 73, 58, 35, 15, 79, 72, 57, 78, 87, 85, 83, 92, 13, 91,
       74, 28,  1, 22, 95, 33, 52, 51, 21, 42, 79, 56, 48, 44, 92],
      dtype=int64)

In [57]:
temperatura = np.random.randint(10,100,100)
lluvia = np.random.randint(10,100, 100)
humedad = np.random.randint(10,100, 100)

In [58]:
data = ['Boat','Car','Bike','Truck']
mount = [1,55,99,43]


In [59]:
newdata = list(zip(data,mount))

In [60]:
newdata

[('Boat', 1), ('Car', 55), ('Bike', 99), ('Truck', 43)]

In [61]:
mydf = pd.DataFrame(newdata, columns = ['thing','count'])
mydf

thing  count
0   Boat      1
1    Car     55
2   Bike     99
3  Truck     43

In [62]:
mydf['thing']

0     Boat
1      Car
2     Bike
3    Truck
Name: thing, dtype: object

In [63]:
mydf[mydf['count']>20]

thing  count
1    Car     55
2   Bike     99
3  Truck     43

In [64]:
mydf.dtypes

thing    object
count     int64
dtype: object

In [65]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [66]:
np.full([3,3,3],32)

array([[[32, 32, 32],
        [32, 32, 32],
        [32, 32, 32]],

       [[32, 32, 32],
        [32, 32, 32],
        [32, 32, 32]],

       [[32, 32, 32],
        [32, 32, 32],
        [32, 32, 32]]])

In [67]:
def main():
    N = int(input())

    str1 = input()
    arr1 = np.array([int(i) for i in str1.split(' ')])
    str2 = input()
    arr2 = np.array([int(i) for i in str2.split(' ')])

    for j in arr1 > arr2:
        if j == False:
            return 0

    return 1

main()

ValueError: invalid literal for int() with base 10: ''

In [ ]:
for i in arr1 > arr2:
    print(i)

True
True
True
False
True


In [ ]:
def f(t):
    return np.cos(t), np.sin(t)

t = np.arange(0, 2 * np.pi, 0.01)

x, y = f(t)

plt.plot(x, y)
plt.title("Círculo unitario")
plt.show()
